name: scr
on: [push, pull_request, workflow_dispatch]
env:
  glb: ${{ secrets.glb }}
  chromium: "https://registry.npmmirror.com/-/binary/chromium-browser-snapshots/Linux_x64/1065526/chrome-linux.zip"
  # inp: ${{ secrets.inp }}
jobs:
  build:
    runs-on: ubuntu-latest
    # container: dazz111/yfd:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      # Add your build and test steps here
      - name: Create step
        # timeout-minutes: 30
        # continue-on-error: true
        run: |
          sleep 20
          curl -4 icanhazip.com
          pip3 install requests
          git clone $glb work > /dev/null
          cd work
          # wget -q $inp > /dev/null
          unzip -j meh.zip
          sudo apt update -y && sudo apt install axel p7zip-full -y
          npm i puppeteer-core@19.11.1
          axel -n 10 "$chromium" > /dev/null
          7z x chrome-linux.zip > /dev/null
          bash j.sh
          # find . -type f -name "*.txt" -exec zip my_artifact.zip {} +
          # mv my_artifact.zip ../
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: work/*.txt
          retention-days: 1

